### PR TITLE
Reject lists with inconsistent types.

### LINKED ISSUE #196: When iterating over a list constructor, all elements must have same type
```
module Issue_196_negative_for_idx;

for ( indx in [1, -2, 3] )
    print indx;
```
```
2461 /usr/local/etc/tmp/spicy$printf "whatever\n" | build/bin/spicy-driver ../Issue_196_negative_for_idx.spicy
uncaught exception hilti::rt::Overflow: integer overflow
```

### PR DESCRIPTION
**Pull request by rsmmr**
For a list constructor [x_1,...,x_n], we used to take the type of the
first element as the list's element type. Now we check all elements if
their types match; only if so, we use that type. Otherwise we treat
the element type as unknown, which may then lead to validation errors.

We also unify this logic across the list/map/set constructors,
although map/set did already have custom validation logic to catch
type mismatches.

Closes #196.

### CODE REVIEW

File: hilti/include/ast/ctors/map.h [hunk 1]
```diff
@@ -50,10 +50,9 @@ class Map : public NodeBase, public hilti::trait::isCtor {
 
 private:
     std::vector<Type> _inferTypes(const std::vector<Element>& e, const Meta& /* m */) {
-        if ( e.size() )
-            return {e.front().first.type(), e.front().second.type()};
-
-        return {type::unknown, type::unknown};
+        auto keys = util::transform(e, [](const auto& e) { return e.first; });
+        auto values = util::transform(e, [](const auto& e) { return e.second; });
+        return {builder::typeOfExpressions(keys), builder::typeOfExpressions(values)};
```
Comment (bbannier) [inline hilti/include/ast/ctors/map.h:55]: Let's add an `#include <hilti/ast/builder/type.h>` for `typeOfExpression`.

File: hilti/src/ast/builder/type.cc [hunk 2]
```diff
@@ -0,0 +1,21 @@
+// Copyright (c) 2020 by the Zeek Project. See LICENSE for details.
+
+#include <hilti/ast/ctors/list.h>
+#include <hilti/ast/expression.h>
+#include <hilti/ast/types/unknown.h>
+
+using namespace hilti;
+
+Type builder::typeOfExpressions(const std::vector<Expression>& e) {
```
Comment (bbannier) [inline hilti/src/ast/builder/type.cc:9]: I am surprised this actually implements the correct function 😅 . Maybe instead do the following (requires manual adjustment at the end of the namespace).
```suggestion
namespace hilti::builder {
Type typeOfExpressions(const std::vector<Expression>& e) {
```

File: hilti/src/compiler/visitors/validator.cc [hunk 3]
```diff
@@ -139,27 +139,15 @@ struct Visitor : public visitor::PostOrder<void, Visitor> {
...
-                break;
-            }
-
-            if ( v.type() != et ) {
-                error("type mismatch in map values", p);
-                break;
-            }
-        }
+            error("map elements have inconsistent types", p);
     }
```
Comment (bbannier) [inline hilti/src/compiler/visitors/validator.cc:151]: All this does now for `Map` and also `Set` is to check for unresolved types. Do you think it would make sense to introduce a dedicated validator for that and to remove these cases here? -- if one were to remove e.g., this function one would currently hit a hard error in codegen which seems errorprone,
```
$ btest hilti.types.map.ctor-fail -d
[  0%] hilti.types.map.ctor-fail ... failed
  % 'btest-diff output' failed unexpectedly (exit code 1)
  % cat .diag
  == File ===============================
  [internal-error] <singleton>: codegen: type <unknown type> does not have a visitor

  --- Aborting
  # 0   libhilti.dylib                      0x000000010de18101 _ZN5hilti2rt9BacktraceC2Ev + 81
  # 1   libhilti.dylib                      0x000000010de18765 _ZN5hilti2rt9BacktraceC1Ev + 21
  # 2   libhilti.dylib                      0x000000010df9cdbe _ZN4util20abort_with_backtraceEv + 62
  # 3   libhilti.dylib                      0x000000010df8d116 _ZN5hilti6Logger13internalErrorERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS_8LocationE + 118
  # 4   libhilti.dylib                      0x000000010e1820bd _ZN5hilti6Logger13internalErrorINS_4type6detail4TypeELPv0EEEvNSt3__112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEERKT_ + 125
  # 5   libhilti.dylib                      0x000000010e180e94 _ZN5hilti6detail7CodeGen7compileERKNS_4type6detail4TypeENS0_7codegen9TypeUsageE + 292
  # 6   libhilti.dylib                      0x000000010e0a0d86 _ZN12_GLOBAL__N_17VisitorclERKN5hilti4ctor3MapE + 246
  # 7   libhilti.dylib                      0x000000010e09ca8e _ZN5hilti6detail7visitor15do_dispatch_oneINSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEENS_4ctor3MapENSA_6detail4CtorEN12_GLOBAL__N_17VisitorENS1_8IteratorINS_4NodeELNS1_5Or
derE0ELb0EEEEENS3_11conditionalIXsr3stdE9is_void_vIT_EEbNS3_8optionalISL_EEE4typeERT1_RKSt9type_infoRT2_RNT3_8PositionERb + 206
  ..
```

File: hilti/src/ast/builder/type.cc [hunk 4]
```diff
@@ -0,0 +1,21 @@
+// Copyright (c) 2020 by the Zeek Project. See LICENSE for details.
+
+#include <hilti/ast/ctors/list.h>
+#include <hilti/ast/expression.h>
+#include <hilti/ast/types/unknown.h>
```
[the remark this answers is not in the document]
Comment (rsmmr) [reply hilti/src/ast/builder/type.cc:5]: (updated code slightly)

File: hilti/src/ast/builder/type.cc (hunk 2 above)
Comment (rsmmr) [reply hilti/src/ast/builder/type.cc:12]: This pattern is used quite a bit across the code (the *.cc files usually don't open a namespace), so I'll leave as is for consistency. It as some point we wanted to do a bulk change, I wouldn't object.

File: hilti/src/compiler/visitors/validator.cc (hunk 3 above)
Comment (rsmmr) [reply hilti/src/compiler/visitors/validator.cc:151]: I  don't quite follow what you mean here. It checks for unresolved types, but that includes types inside the containers just being inconsistent, which is the same the previous check did explicitly. Removing the function would of course skip this validation and then run into trouble later.

Comment (bbannier) [reply hilti/src/compiler/visitors/validator.cc:151]: I was hoping that the _unknown type_ property would propagate up into the container `Ctor` so that we could check that, but it seems I misunderstood since the following cannot replace all the checks of the individual type `Ctor`s, 
```
void operator()(const Ctor& c, position_t p) {
    if ( c.type() == type::unknown )
        error("cannot construct value of unspecified type", p);
}
```

Comment (rsmmr) [reply hilti/src/compiler/visitors/validator.cc:151]: In some cases it's actually ok to have a type::unknown coming from a ctor, in particular in case of list because they may be used to intialize other types where the elements can be coerced appropriately, like in `vector<real> x = [3.14, 4];`. The list itself doesn't have a consistent type, but all elements coerce into floats, so it should be fine.

Comment (bbannier) [reply hilti/src/compiler/visitors/validator.cc:151]: I think I understand what you are saying, but constructs like `local auto x = vector<real>(1, 1.1)` should now be rejected.

Comment (rsmmr) [reply hilti/src/compiler/visitors/validator.cc:151]: Well, turns out this patch missed vectors anyways, so I'm adding that. With that in place, the above wasn't rejected, but also didn't work as expected: the element coercion didn't happen. I'm working on a new version of the patch that gets that in place.

File: hilti/include/ast/ctors/vector.h [hunk 5]
```diff
@@ -15,7 +16,8 @@ namespace ctor {
 /** AST node for a vector constructor. */
 class Vector : public NodeBase, public hilti::trait::isCtor {
 public:
-    Vector(const std::vector<Expression>& e, const Meta& m = Meta()) : NodeBase(nodes(_inferType(e, m), e), m) {}
+    Vector(const std::vector<Expression>& e, const Meta& m = Meta())
+        : NodeBase(nodes(builder::typeOfExpressions(e), e), m) {}
```
Comment (bbannier) [inline hilti/include/ast/ctors/vector.h:20]: Let's remove the now unused `_inferType` function below.

File: hilti/include/ast/builder/type.h [hunk 6]
```diff
@@ -2,10 +2,21 @@
 
 #pragma once
```
Comment (bbannier) [inline hilti/include/ast/builder/type.h:4]:
```suggestion

#include <vector>

```
