### PR TITLE
Remove internal errors that we ended up running into during AST valid…

### LINKED ISSUE #192: operator left unresolved produces `Abort trap: 6`
```
module Issue_192_isLHS_Abort_trap;

public type IMSIunit = unit(label: string, contentExceptLast: bytes, lastbyte: uint8) {
  on %init {
    shortened(contentExceptLast);
  }
};

function shortened(contentExceptLast: bytes) {
  for (idx in contentExceptLast) {
    retString = retString + "%02X" %
    label = label + "%02X" % unSignExtended;
  }
}
```
produces:
```
2369 /usr/local/etc/tmp/spicy$printf "1\n" | build/bin/spicy-driver ../Issue_192_isLHS_Abort_trap.spicy
[error] ../Issue_192_isLHS_Abort_trap.spicy:11: unknown ID 'retString'
[error] ../Issue_192_isLHS_Abort_trap.spicy:12: unknown ID 'label'
[error] ../Issue_192_isLHS_Abort_trap.spicy:11-12: operator left unresolved
[error] ../Issue_192_isLHS_Abort_trap.spicy:11-12: operator left unresolved
[error] ../Issue_192_isLHS_Abort_trap.spicy:12: operator left unresolved
[error] ../Issue_192_isLHS_Abort_trap.spicy:12: operator left unresolved
[internal-error] UnresolvedOperator::isLhs() not supported

--- Aborting
# 0   libhilti.dylib                      0x0000000108b6a3c4 _ZN5hilti2rt9BacktraceC2Ev + 84
# 1   libhilti.dylib                      0x00000001083b1f18 _ZN4util20abort_with_backtraceEv + 136
# 2   libhilti.dylib                      0x00000001083acce0 _ZN5hilti6Logger13internalErrorERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS_8LocationE + 64
# 3   libspicy.dylib                      0x0000000107acaea2 _ZNK5hilti10expression18UnresolvedOperator5isLhsEv + 210
# 4   libhilti.dylib                      0x00000001086fde94 _ZN5hilti6detail7visitor11do_dispatchIvKNS_4NodeEN12_GLOBAL__N_17VisitorENS1_8IteratorIS3_LNS1_5OrderE1ELb1EEEEENSt3__111conditionalIXsr3stdE9is_void_vIT_EEbNSA_8optionalISC_EEE4typeERT0_RT1_RNT2_8PositionERb + 2644
# 5   libhilti.dylib                      0x00000001086fc8af _ZL12_validateASTRKN5hilti4NodeEb + 991
# 6   libhilti.dylib                      0x00000001085705d8 _Z8runHooksIMN5hilti6PluginENSt3__18optionalINS2_8functionIFvNS2_10shared_ptrINS0_7ContextEEERKNS0_4NodeEPNS0_4UnitEEEEEEJS7_S8_SC_EEbT_RKNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEDpRKT0_ + 616
# 7   libhilti.dylib                      0x000000010856e3f5 _ZN5hilti4Unit7compileEv + 8437
# 8   libhilti.dylib                      0x0000000108552114 _ZN5hilti6Driver12_compileUnitENS_4UnitE + 836
# 9   libhilti.dylib                      0x0000000108552fe4 _ZN5hilti6Driver12compileUnitsEv + 852
# 10  libhilti.dylib                      0x000000010855466a _ZN5hilti6Driver7compileEv + 42
# 11  spicy-driver                        0x00000001079d8326 main + 118
# 12  libdyld.dylib                       0x00007fff669e77fd start + 1
# 13  ???                                 0x0000000000000002 0x0 + 2
Abort trap: 6
```

### PR DESCRIPTION
**Pull request by rsmmr**
…ation.

The AST will eventually be rejected anyways, so doesn't matter what we
return in those methods.

Closes #192.

### CODE REVIEW

File: hilti/include/ast/expressions/unresolved-operator.h [hunk 1]
```diff
@@ -25,9 +25,9 @@ class UnresolvedOperator : public NodeBase, public trait::isExpression {
     }
 
     /** Implements `Expression` interface. */
```
Comment (bbannier) [inline hilti/include/ast/expressions/unresolved-operator.h:27]: Nice, now almost all methods in this block are dummy-impls. Let's add a comment 
```suggestion
    /** Implements `Expression` interface. */
    
    // Dummy implementations as the node will be rejected in validation anyway.
```

and an empty line before the `isEqual` impl (could also remove l.37 so dummy and real impls are in blocks, each).
