### PR TITLE
Disallow function redef with different returns but same parameters

### LINKED ISSUE #1977: Defining the same identifier twice leads to a large error trace
Consider the following:

```spicy
function fib(n: uint64, inout cache: map<uint64, uint64>): void {
    return;
}

function fib(n: uint64, inout cache: map<uint64, uint64>): uint64 { 
return 0;
}
``` 

Produces this output:
```
/tmp/hello_22414bd86b0d226d-aec19e941cd943fe.cc:14:17: error: ambiguating new declaration of ‘hilti::rt::integer::safe<long unsigned int> __hlt::hello::fib(hilti::rt::integer::safe<long unsigned int>&, hilti::rt::Map<SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException>, SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException> >&)’
   14 |     static auto fib(const ::hilti::rt::integer::safe<uint64_t>& n, ::hilti::rt::Map<::hilti::rt::integer::safe<uint64_t>, ::hilti::rt::integer::safe<uint64_t>>& cache) -> ::hilti::rt::integer::safe<uint64_t>;
      |                 ^~~
/tmp/hello_22414bd86b0d226d-aec19e941cd943fe.cc:13:17: note: old declaration ‘void __hlt::hello::fib(hilti::rt::integer::safe<long unsigned int>&, hilti::rt::Map<SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException>, SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException> >&)’
   13 |     static void fib(const ::hilti::rt::integer::safe<uint64_t>& n, ::hilti::rt::Map<::hilti::rt::integer::safe<uint64_t>, ::hilti::rt::integer::safe<uint64_t>>& cache);
      |                 ^~~
/tmp/hello_22414bd86b0d226d-aec19e941cd943fe.cc: In function ‘void __hlt::hello::__init_module()’:
/tmp/hello_22414bd86b0d226d-aec19e941cd943fe.cc:29:27: error: invalid use of void expression
   29 |     ::hilti::rt::print(fib(::hilti::rt::integer::safe<std::uint64_t>{64U}, (*__hlt::hello::m_fib)), ::hilti::rt::Bool(true));
      |                        ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/hello_22414bd86b0d226d-aec19e941cd943fe.cc: At global scope:
/tmp/hello_22414bd86b0d226d-aec19e941cd943fe.cc:40:204: error: ‘hilti::rt::integer::safe<long unsigned int> __hlt::hello::fib(hilti::rt::integer::safe<long unsigned int>&, hilti::rt::Map<SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException>, SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException> >&)’ should have been declared inside ‘__hlt::hello’
   40 | static auto __hlt::hello::fib(const ::hilti::rt::integer::safe<uint64_t>& n, ::hilti::rt::Map<::hilti::rt::integer::safe<uint64_t>, ::hilti::rt::integer::safe<uint64_t>>& cache) -> ::hilti::rt::integer::safe<uint64_t> { ::hilti::rt::detail::checkStack(); }
      |                                                                                                                                                                                                            ^~~~~~~~~~~~~~
/tmp/hello_22414bd86b0d226d-aec19e941cd943fe.cc:40:13: error: ambiguating new declaration of ‘hilti::rt::integer::safe<long unsigned int> __hlt::hello::fib(hilti::rt::integer::safe<long unsigned int>&, hilti::rt::Map<SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException>, SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException> >&)’
   40 | static auto __hlt::hello::fib(const ::hilti::rt::integer::safe<uint64_t>& n, ::hilti::rt::Map<::hilti::rt::integer::safe<uint64_t>, ::hilti::rt::integer::safe<uint64_t>>& cache) -> ::hilti::rt::integer::safe<uint64_t> { ::hilti::rt::detail::checkStack(); }
      |             ^~~~~
/tmp/hello_22414bd86b0d226d-aec19e941cd943fe.cc:34:13: note: old declaration ‘void __hlt::hello::fib(hilti::rt::integer::safe<long unsigned int>&, hilti::rt::Map<SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException>, SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException> >&)’
   34 | static void __hlt::hello::fib(const ::hilti::rt::integer::safe<uint64_t>& n, ::hilti::rt::Map<::hilti::rt::integer::safe<uint64_t>, ::hilti::rt::integer::safe<uint64_t>>& cache) {
      |             ^~~~~
/tmp/hello_22414bd86b0d226d-aec19e941cd943fe.cc: In function ‘hilti::rt::integer::safe<long unsigned int> __hlt::hello::fib(hilti::rt::integer::safe<long unsigned int>&, hilti::rt::Map<SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException>, SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException> >&)’:
/tmp/hello_22414bd86b0d226d-aec19e941cd943fe.cc:40:256: warning: no return statement in function returning non-void [-Wreturn-type]
   40 | static auto __hlt::hello::fib(const ::hilti::rt::integer::safe<uint64_t>& n, ::hilti::rt::Map<::hilti::rt::integer::safe<uint64_t>, ::hilti::rt::integer::safe<uint64_t>>& cache) -> ::hilti::rt::integer::safe<uint64_t> { ::hilti::rt::detail::checkStack(); }
      |                                                                                                                                                                                                                                                                ^
[error] spicyc: JIT compilation failed
```

This is not a grave error, but maybe it could be improved?

### PR DESCRIPTION
**Pull request by evantypanski**
Fixes #1977

C++ doesn't allow different return types with equivalent parameters, so Spicy should grab that and error before it gets to the C++ error.

### CODE REVIEW

File: hilti/toolchain/src/compiler/validator.cc [hunk 1]
```diff
@@ -204,10 +204,22 @@ struct VisitorPost : visitor::PreOrder, public validator::VisitorMixIn {
...
+                        auto current_fn_ty = current_decl->function()->ftype();
+                        auto previous_fn_ty = previous_decl->function()->ftype();
+
+                        // Overloads cannot differ in return type only.
+                        if ( ! type::same(current_fn_ty->result(), previous_fn_ty->result()) &&
+                             hilti::declaration::areEquivalent(current_fn_ty->parameters(),
+                                                               previous_fn_ty->parameters()) )
+                            error(fmt("'%s' only differs in return type from previous definition in %s", id,
+                                      first_node->location()),
+                                  node);
```
Comment (bbannier) [inline hilti/toolchain/src/compiler/validator.cc:219]: WDYT about introducing a dedicated function to check for valid overloads, e.g., a function `bool areOverloads(Function*, Function*)` next to `Function`'s `areEquivalent` which we could use here? Alternative we could introduce a dedicated function `checkOverload` similar to `VisitorMixIn::checkTypeArguments` which encapsulates validation of overloads. Even though the latter might allow better error messages I feel the first one might be better since it could be easier to reuse, e.g., in the resolver.

File: hilti/toolchain/include/ast/declarations/parameter.h [hunk 2]
```diff
@@ -133,4 +133,10 @@ inline bool areEquivalent(Parameter* p1, Parameter* p2) {
     return type::same(p1->type(), p2->type());
 }
 
+/** Returns true if two sets of parameters are equivalent, regardless of their ID. */
+inline bool areEquivalent(node::Set<Parameter> params1, node::Set<Parameter> params2) {
```
Comment (bbannier) [inline hilti/toolchain/include/ast/declarations/parameter.h:137]: No need for copies here.

```suggestion
inline bool areEquivalent(const node::Set<Parameter>& params1, const node::Set<Parameter>& params2) {
```

File: hilti/toolchain/include/ast/declarations/parameter.h [hunk 3]
```diff
@@ -133,4 +133,10 @@ inline bool areEquivalent(Parameter* p1, Parameter* p2) {
...
+    return std::equal(std::begin(params1), std::end(params1), std::begin(params2), std::end(params2),
```
Comment (bbannier) [inline hilti/toolchain/include/ast/declarations/parameter.h:138]: Nit: We don't need non-member `begin`/`end` here and using it makes the line longer.

```suggestion
    return std::equal(params1.begin(), params1.end(), params2.begin(), params2.end(),
```

**Review by bbannier — APPROVED** [review]

File: hilti/toolchain/src/compiler/validator.cc (hunk 1 above)
Comment (bbannier) [reply hilti/toolchain/src/compiler/validator.cc]: Thanks for the issue, IMO totally fine to do tackle this one problem at a time.
