### PR TITLE
Fix comment parsing in EVT files.

### LINKED ISSUE #312: Comments in EVT files aren't parsed correctly
This is not finding the `;` terminating the block.

```
protocol analyzer spicy::TFTP over UDP:
    parse with TFTP::Message,   # entry point for parsing TFTP payload
    port 69/udp;                # use analyzer for sessions on UDP port 69
```

### PR DESCRIPTION
**Pull request by rsmmr**
The fix is quite involved because the parser is really just a hack
right now, and we need to add state machine to track whether we are
inside a comment. We need to switch to a flex/bison parser here
eventually.

We use new comments inside tftp.evt as our test, that used to be not
working.

Closes #312.

### CODE REVIEW

File: zeek/compiler/glue-compiler.cc [hunk 1]
```diff
@@ -235,6 +235,73 @@ GlueCompiler::GlueCompiler(Driver* driver) : _driver(driver) {}
...
+    std::string chunk;
+
+    // Parser need to track whether we are inside a string or a comment.
+    enum State { Default, InComment, InString } state = Default;
+    char prev = '\0';
+
+    while ( true ) {
+        char cur;
+        in.get(cur);
+        if ( in.eof() ) {
```
Comment (bbannier) [inline zeek/compiler/glue-compiler.cc:248]: nit: can write this shorter

```suggestion
        if ( in.get(cur) ) {
```

File: zeek/compiler/glue-compiler.cc [hunk 2]
```diff
@@ -235,6 +235,73 @@ GlueCompiler::GlueCompiler(Driver* driver) : _driver(driver) {}
 
 GlueCompiler::~GlueCompiler() {}
 
+hilti::Result<std::string> GlueCompiler::getNextEvtBlock(std::istream& in, int* lineno) {
```
Comment (bbannier) [inline zeek/compiler/glue-compiler.cc:238]: Can be `const` (also in decl).
```suggestion
hilti::Result<std::string> GlueCompiler::getNextEvtBlock(std::istream& in, int* lineno) const {
```

File: zeek/compiler/glue-compiler.cc (hunk 1 above)
Comment (rsmmr) [reply zeek/compiler/glue-compiler.cc]: Turns out this doesn't work, reverted.
