### PR TITLE
Fix release tarball

### LINKED ISSUE #943: Issues with source tar ball
Our release tgz of the source code (`spicy.tar.gz`)has a couple of issues:

- It doesn't have a top-level `spicy` directory, unpacks directly into the current directory. It should unpack into `spicy-<version>/`.

- When building it reports:

```
/Users/robin/tmp/x/scripts/autogen-version --header /Users/robin/tmp/x/build/include/hilti/rt/autogen/version.h --git-root /Users/robin/tmp/x
Traceback (most recent call last):
  File "/Users/robin/tmp/x/scripts/autogen-version", line 155, in <module>
    major, minor, patch, *_ = version.split(".")
ValueError: not enough values to unpack (expected at least 3, got 1)
[16/338] Building CXX object 3rdparty/benchmark/src/CMakeFiles/benchmark.dir/benchmark_register.cc.o
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by bbannier**
Closes #943.

### CODE REVIEW

File: scripts/make-tarball.sh [hunk 1]
```diff
@@ -17,5 +17,14 @@ git submodule foreach --quiet 'cd $toplevel && tar rf '"${TARBALL}"' $sm_path'
 ./scripts/autogen-version --store VERSION
 tar rf "${TARBALL}" VERSION
 
-# Compress archive.
-gzip -9 "${TARBALL}"
+# Introduce a top-level `spicy` directory and compress the tarball.
+SCRATCH=$(mktemp -d)
+mkdir "${SCRATCH}/spicy"
```
Comment (rsmmr) [inline scripts/make-tarball.sh:22]: Please include the version number into the directory name as well (as we do already for the binary tgzs).

**Review by rsmmr — CHANGES_REQUESTED** [review]

**Review by rsmmr — APPROVED** [review]
