### PR TITLE
Fix potential nullptr dereference when comparing streams.

### LINKED ISSUE #1875: Generated code segfaults when `%synchronize-after` appears at the end of input
The following produces a segfault when run:

```
module RESP;

public type Datas = unit {
    : (Data &synchronize)[];
};

type Data = unit {
    %synchronize-after=b"a";
    ty: uint8 &requires=($$ < 5);
    };
```

Input:

```
$ printf "ba" | spicy-driver test.spicy
[1]    36912 done                printf "ba" |
       36913 segmentation fault  spicy-driver test.spicy
```

The necessary conditions are just triggering the `synchronize-after` such that it will attempt to go after the input, it seems. If the `synchronize-after` condition is never matched it exits with an exception, which seems reasonable. For example this works as I would expect:

```
$ printf "bb" | spicy-driver test.spicy
[error] terminating with uncaught exception of type spicy::rt::ParseError: failed to synchronize: &requires failed: ($$ < 5) (test.spicy:9:15-9:32)
```

### PR DESCRIPTION
**Pull request by rsmmr**
Because we are operating on unsafe iterators, need to catch when one
goes out of bounds.

Closes #1875.

### CODE REVIEW

File: hilti/runtime/src/types/stream.cc [hunk 1]
```diff
@@ -586,6 +589,9 @@ bool stream::View::operator==(const Bytes& other) const {
     auto j = other.begin();
 
     while ( i != unsafeEnd() ) {
+        if ( ! i.chunk() ) // out-of-bounds, cannot  match
```
Comment (bbannier) [inline hilti/runtime/src/types/stream.cc:592]:
```suggestion
        if ( ! i.chunk() ) // out-of-bounds, cannot match
```

File: .typos.toml [hunk 2]
```diff
@@ -5,3 +5,5 @@ inout = "inout"
 ocur = "ocur"
 bigsur = "Big Sur"
 Smoot = "Smoot"
+ba = "ba"
+Datas = "Datas"
```
Comment (bbannier) [inline .typos.toml:9]: Nit: TBH, since it is so unlikely we'd use the identifiers again I'd probably just use different data in the test and renamed the top-level unit to e.g., `Messages` than add these here.

**Review by bbannier — APPROVED** [review]

File: .typos.toml (hunk 2 above)
Comment (rsmmr) [reply .typos.toml:9]: Would also require changing input here.
