### PR TITLE
Fix "foreach" inside a unit hook.

### LINKED ISSUE #583: foreach only works when inline
foreach to execute the handler on each item works when inline, as
```
module Issue_582;

type Line = unit {
    var paraMarker: bool;
  lin: /[^\n]*/;
    on lin {
      if (0 == |self.lin|) {
        self.paraMarker = True;
      }
    }
  crlfIfPresent: /\n/;
    on %done {
      print (self);
    }
};

public type CollectionOfLines = unit {
    var firstSection: bool = True;
    var firstNonHeader: bool = False;
    var lineContent: Line;
  lins: Line[] foreach {
      if (self.firstSection && $$.paraMarker) {
      	print ("header: %s" % ($$,));
        self.firstSection = False;
        self.firstNonHeader = True;
      }
      else if (self.firstNonHeader && $$.paraMarker) {
      	print ("non header: %s" % ($$,));
        self.firstNonHeader = False;
      }

    }
};

```
produces
```
/spicy-0.4.0-884/spicy/build/bin/spicy-driver -f ../data/2020_simple.dat /usr/local/etc/tmp/Issue_582_foreach_inline.spicy
[$paraMarker=False, $lin=b"H1", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"H2", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"H3", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
header: [$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"1", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
non header: [$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"2", $crlfIfPresent=b"\x0a"]
 . . .
```
but a non-inline arrangement:
```
module Issue_582;

type Line = unit {
    var paraMarker: bool;
  lin: /[^\n]*/;
    on lin {
      if (0 == |self.lin|) {
        self.paraMarker = True;
      }
    }
  crlfIfPresent: /\n/;
    on %done {
      print (self);
    }
};

public type CollectionOfLines = unit {
    var firstSection: bool = True;
    var firstNonHeader: bool = False;
    var lineContent: Line;
  lins: Line[];
    on lins foreach {
      if (self.firstSection && $$.paraMarker) {
      	print ("header: %s" % ($$,));
        self.firstSection = False;
        self.firstNonHeader = True;
      }
      else if (self.firstNonHeader && $$.paraMarker) {
      	print ("non header: %s" % ($$,));
        self.firstNonHeader = False;
      }
    }
};
```
produces
```
./spicy-0.4.0-884/spicy/build/bin/spicy-driver -f ../data/2020_simple.dat /usr/local/etc/tmp/Issue_582_foreach.spicy
[error] /usr/local/etc/tmp/Issue_582_foreach.spicy:23:32: unsupported operator: <<unknown type>>.<<member>>
[error] /usr/local/etc/tmp/Issue_582_foreach.spicy:24:15: unsupported operator: <string> % <<unknown type>>
[error] /usr/local/etc/tmp/Issue_582_foreach.spicy:28:39: unsupported operator: <<unknown type>>.<<member>>
[error] /usr/local/etc/tmp/Issue_582_foreach.spicy:29:15: unsupported operator: <string> % <<unknown type>>
[error] spicy-driver: aborting after errors
```
while eliminating the $$ as
```
module Issue_582;

type Line = unit {
    var paraMarker: bool;
  lin: /[^\n]*/;
    on lin {
      if (0 == |self.lin|) {
        self.paraMarker = True;
      }
    }
  crlfIfPresent: /\n/;
    on %done {
      print (self);
    }
};

public type CollectionOfLines = unit {
    var firstSection: bool = True;
    var firstNonHeader: bool = False;
    var lineContent: Line;
  lins: Line[];
    on lins foreach {
      if (self.firstSection) {
      	print ("header: %s" % (self.lins[|self.lins| - 1],));
        self.firstSection = False;
        self.firstNonHeader = True;
      }
      else if (self.firstNonHeader) {
      	print ("non header: %s" % (self.lins[|self.lins| - 1],));
        self.firstNonHeader = False;
      }
    }
};
```
and thus remedying the syntax errors, produces different behavior with the evaluation only taking place at the end, and executing the handler only once
```
1696> ./spicy-0.4.0-884/spicy/build/bin/spicy-driver -f ../data/2020_simple.dat /usr/local/etc/tmp/Issue_582_foreach_no_dolrdolr.spicy
[$paraMarker=False, $lin=b"H1", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"H2", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"H3", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"1", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"2", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"3", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"4", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"5", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"6", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"7", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"8", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"9", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"10", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"11", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"12", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"13", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"14", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"15", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"16", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"17", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"18", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"19", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"20", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"21", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"22", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"23", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"24", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"25", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"26", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"27", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"28", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=False, $lin=b"29", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
[$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
header: [$paraMarker=True, $lin=b"", $crlfIfPresent=b"\x0a"]
1697> ./spicy-0.4.0-884/spicy/build/bin/spicy-driver --v
spicy-driver v0.4.0-884.dirty (master 6b77b11)

### PR DESCRIPTION
**Pull request by rsmmr**
Two issues:
    1. The "foreach" attribute wasn't passed on.
    2. The '$$' lookup didn't work inside a non-inline hook.

Closes #583.

### CODE REVIEW

File: spicy/toolchain/src/compiler/visitors/id-resolver.cc [hunk 1]
```diff
@@ -112,40 +112,51 @@ struct Visitor2 : public hilti::visitor::PostOrder<void, Visitor2> {
...
-            auto f = p.findParent<type::unit::item::Field>();
+            std::optional<Type> dd;
 
-            if ( ! f )
-                return;
+            if ( auto f = p.findParent<hilti::Function>() ) {
+                for ( const auto& p : f->get().type().parameters() ) {
+                    if ( p.id() == ID("__dd") )
+                        // Inside a free function that defines a "__dd" parameter; use it.
+                        dd = hilti::type::Computed(hilti::builder::id("__dd"));
```
Comment (bbannier) [inline spicy/toolchain/src/compiler/visitors/id-resolver.cc:121]: Can we jump out of the loop here?

**Review by bbannier — DISMISSED** [review]

**Review by bbannier — APPROVED** [review]
