### PR TITLE
Declare types used in globals before using them.

### LINKED ISSUE #1030: C++ code initialization globals emitted before types are fully declared
Compiling the following sample currently fails:

```.ruby
# c.hlt
module c {

public type a = struct {};

global a x;

}
```

```.console
$ hiltic -j c.hlt
/private/var/folders/ht/vtb0rkbd4ws15vx02xdb84zw0000gn/T/hilti-rt-test-corFCB/c.cc:18:11: error: field has incomplete type '__hlt::c::a'
        a x{};
          ^
/private/var/folders/ht/vtb0rkbd4ws15vx02xdb84zw0000gn/T/hilti-rt-test-corFCB/c.cc:9:12: note: forward declaration of '__hlt::c::a'
    struct a;
           ^
In file included from /private/var/folders/ht/vtb0rkbd4ws15vx02xdb84zw0000gn/T/hilti-rt-test-corFCB/c.cc:1:
In file included from /Users/bbannier/src/spicy/hilti/runtime/include/hilti/rt/libhilti.h:9:
In file included from /Users/bbannier/src/spicy/build/include/hilti/rt/autogen/config.h:5:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/c++/v1/string:504:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/c++/v1/string_view:175:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/c++/v1/__string:57:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/c++/v1/algorithm:643:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/c++/v1/memory:3866:24: error: assigning to 'std::__1::__shared_weak_count *' from incompatible type
      'std::__1::__shared_ptr_emplace<__hlt::c::__globals_t, std::__1::allocator<__hlt::c::__globals_t> > *'
        __r.__cntrl_ = __cntrl;
                       ^~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/c++/v1/memory:4408:29: note: in instantiation of function template specialization
      'std::__1::shared_ptr<__hlt::c::__globals_t>::__create_with_control_block<__hlt::c::__globals_t, std::__1::__shared_ptr_emplace<__hlt::c::__globals_t, std::__1::allocator<__hlt::c::__globals_t> > >' requested here
    return shared_ptr<_Tp>::__create_with_control_block(__ptr, __hold2.release());
                            ^
/Users/bbannier/src/spicy/hilti/runtime/include/hilti/rt/global-state.h:124:59: note: in instantiation of function template specialization 'std::__1::make_shared<__hlt::c::__globals_t>' requested here
    context::detail::current()->hilti_globals[idx] = std::make_shared<T>();
                                                          ^
2 errors generated.
[error] hiltic: JIT compilation failed
```

This seems to be due to the order of the emitted definitions in the generated C++ code:

```.cpp
// ...

namespace __hlt::c {
    struct a;
}

// ...

namespace __hlt::c {
    struct __globals_t : hilti::rt::trait::isStruct, hilti::rt::Controllable<__globals_t> {
        a x{};
        template<typename F> void __visit(F _) const { _("x", x); }
    };

    struct a : hilti::rt::trait::isStruct, hilti::rt::Controllable<a> {
        inline auto __self() { return hilti::rt::ValueReference<a>::self(this); }

// ...

```

Here the definition of `__globals_t` cannot create a `a` since at that point the type has only been forward-declared.

This currently probably is not an issue for Spicy code as we wrap most values of user-specified type in some reference.

### PR DESCRIPTION
**Pull request by bbannier**
Closes #1030.

### CODE REVIEW

File: hilti/toolchain/src/compiler/codegen/codegen.cc [hunk 1]
```diff
@@ -149,8 +146,14 @@ struct GlobalsVisitor : hilti::visitor::PreOrder<void, GlobalsVisitor> {
...
         assert(n.typeID());
         cg->compile(n.type(), codegen::TypeUsage::Storage);
-        if ( include_implementation )
+        if ( include_implementation ) {
             cg->addTypeInfoDefinition(n.type());
+
+            if ( const auto& dt = cg->typeDeclaration(n.type()) ) {
+                auto* unit = cg->unit();
+                unit->prioritizeType(dt->id);
+            }
```
Comment (rsmmr) [inline hilti/toolchain/src/compiler/codegen/codegen.cc:155]:
```suggestion
            if ( const auto& dt = cg->typeDeclaration(n.type()) )
                cg->unit()->prioritizeType(dt->id);
```

**Review by rsmmr — APPROVED** [review]
