### PR TITLE
Document arguments to `new` operator.

### LINKED ISSUE #1063: Units cannot have sink fields which take parameters
Trying this:

```
public type Someunit = unit(arg1: string, arg2: string) {
    len: uint32;
    payload: bytes &size=self.len -> self.AnotherUnit;
    sink AnotherUnit(arg1, arg2);
};
```

gives an error such as this on the `sink AnotherUnit(arg1, arg2)` line above:

```
analyzer.spicy:148:13: syntax error, unexpected '(', expecting attribute or ';'
```

### PR DESCRIPTION
**Pull request by rsmmr**
Closes #1063.

### CODE REVIEW

File: hilti/toolchain/src/ast/operators/generic.cc [hunk 1]
```diff
@@ -286,11 +286,13 @@ class New : public Operator {
...
-Returns a :ref:`reference <type_reference>` to an instance of a type newly
-allocated on the heap. If ``T`` is a type, a default instance of that type will
-be allocated. If ``T`` is a constant, an instance of its type will be
-allocated and initialized with the value. Other types of expressions are not
-allowed.
+Returns a :ref:`reference <type_reference>` to an instance of a type
+newly allocated on the heap. If ``T`` is a type, a default instance of
+that type will be allocated. If the type expects any parameters, they
+must be provided through a corresponding argument tuple: ``new
+T(ARG_1,...ARG_N)``. If ``T`` is a constant, an instance of its type
```
Comment (evantypanski) [inline hilti/toolchain/src/ast/operators/generic.cc:293]:
```suggestion
T(ARG_1, ... ,ARG_N)``. If ``T`` is a constant, an instance of its type
```

Nit: [other](https://docs.zeek.org/projects/spicy/en/latest/programming/language/types.html#enum) [places](https://docs.zeek.org/projects/spicy/en/latest/programming/language/types.html#enum) seem to use commas after the `...` too. I'd also prefer spaces around it

**Review by evantypanski — DISMISSED** [review]
LGTM 🤷

File: hilti/toolchain/src/ast/operators/generic.cc (hunk 1 above)
Comment (rsmmr) [reply hilti/toolchain/src/ast/operators/generic.cc:293]: Ack, consistency is good!

**Review by bbannier — APPROVED** [review]
