### PR TITLE
Reject joint usage of filters and look-ahead.

### LINKED ISSUE #1655: Filter generates code with incompatible iterators
Using the filter or not in the following example should not make a difference, however the version with connected filter throws an error from generated code.

```ruby
# @TEST-EXEC: echo "foo" | spicy-dump -d %INPUT 1>&2

module foo;

public type X = unit {
    headers: Y[];
};

type Y = unit {
    on %init {
        self.connect_filter(new F);
    }

    : b"foo";
};

type F = unit {
    %filter;
    : bytes &eod {
        self.forward($$);
    }
};
```

```
[fatal error] terminating with uncaught exception of type hilti::rt::InvalidIterator: incompatible iterator (../filter-fail.spicy:14:7)
```

This seems to have been broken since at least v1.2.0.

### PR DESCRIPTION
**Pull request by rsmmr**
- **Add test confirming that `&parse-{at,from}` don't interfere with outer look-ahead parsing.**
- **Reject joint usage of filters and look-ahead.**

Closes #1655.

### CODE REVIEW

File: spicy/toolchain/include/ast/types/unit.h [hunk 1]
```diff
@@ -80,9 +80,22 @@ class Unit : public UnqualifiedType {
...
+     * from actual use of the type inside the global AST and will be valid only
+     * after the Spicy resolver has finished.
+     */
+    auto mayHaveFilter() const { return _may_have_filter; }
+
+    /**
+     * Sets the flag indicating whether the unit may see a filter getting
+     * attached. Should be called only by the resolver.
+     */
+    void setMayHaveFilter(bool may_have_filter) { _may_have_filter = may_have_filter; }
```
Comment (bbannier) [inline spicy/toolchain/include/ast/types/unit.h:97]: Currently we never unset this (and I suspect it would be difficult since filters could be removed in a number of ways), so for now we could make this a one-way toggle, e.g.,

```suggestion
    void setMayHaveFilter() { _may_have_filter = true; }
```

**Review by bbannier — APPROVED** [review]

File: spicy/toolchain/include/ast/types/unit.h (hunk 1 above)
Comment (rsmmr) [reply spicy/toolchain/include/ast/types/unit.h:97]: As a general pattern I like to pass booleans to functions so that one can go both ways.
