### PR TITLE
Fix code generation when a module's file could be imported through

### LINKED ISSUE #1227: Chained import with `import ... from ...` generates invalid C++ names
The following reproducer with chained imports produces names which cannot be found. Looking at the generated name it looks like this is due to us generating namespace names for hooks by concatenating the module names in the import chain, but use types in simple namespaces.

```ruby
# @TEST-EXEC: spicyc -d -j z.spicy -o z.hlto

module z;
import y;

@TEST-START-FILE y.spicy
module y;
import x from bla;
@TEST-END-FILE

@TEST-START-FILE bla/x.spicy
module x;

type X = unit {
	on %done {}
};
@TEST-END-FILE
```

Bisecting with this reproducer points to #1195 as the change introducing this regression.

### PR DESCRIPTION
**Pull request by rsmmr**
different means.

This can happen when mixing normal import with  `import ... from`. A
previous change to support multiple units of the same name, missed
that we could run into namespacing trouble at code generation time in
this case. The problem was that we included the `from ...` scope into
the namespace, which doesn't work when we import the same module both
w/ and wo/ scope. Now we generate unique module IDs differently
through global state independent of file system paths.

Close #1227.

### CODE REVIEW

**Comment by bbannier** [comment]
@rsmmr, now to `v1.5.0` has been released, can we merge this into `main`? That would allow us to soak this patch for possible inclusion in `v1.5.1` as well.

File: hilti/toolchain/src/compiler/unit.cc [hunk 1]
```diff
@@ -47,6 +49,16 @@ bool runHook(bool* modified, const Plugin& plugin, const Node* module, const std
     return logger().errors() == 0;
 }
 
+ID Unit::_makeUniqueID(const ID& id) {
+    ID uid;
```
Comment (bbannier) [inline hilti/toolchain/src/compiler/unit.cc:53]: This seems to be unused.
```suggestion
```

File: hilti/toolchain/include/compiler/unit.h [hunk 2]
```diff
@@ -407,13 +410,16 @@ class Unit {
...
+    ID _unique_id;                                  // globally unique ID for this module
     hilti::rt::filesystem::path _extension;         // AST extension, which may differ from source file
     std::optional<Node> _module;                    // root node for AST (always a `Module`), if available
     std::vector<std::weak_ptr<Unit>> _dependencies; // recorded dependencies
     std::weak_ptr<Context> _context;                // global context
     std::optional<detail::cxx::Unit> _cxx_unit;     // compiled C++ code for this unit, once available
     bool _resolved = false;                         // state of resolving the AST
     bool _requires_compilation = false;             // mark explicitly as requiring compilation to C++
+
+    static std::map<ID, unsigned int> _uid_cache; // cache storing state for generating globally unique IDs
```
Comment (bbannier) [inline hilti/toolchain/include/compiler/unit.h:422]: Since `ID` is hashable we could use a `std::unordered_map` here. This wouldn't cost us anything, but could give minor speedups for compilations using a lot of units.

**Review by bbannier — APPROVED** [review]

**Comment by bbannier** [comment]
Landed in both `main` and `release/1.5`.
