### PR TITLE
Fix handling of `%synchronize-*` attributes for units in lists.

### LINKED ISSUE #1617: Use of `%synchronize-at` unexpectedly rejected
One would expect that the following code can be used to specify a literal to synchronize on independently of usual lookahead parsing:

```ruby
module sync;

public type PDUs = unit {
    : (PDU &synchronize)[];
    on %synced { confirm; }
};

type PDU = unit {
    %synchronize-at = b"\x00";
    : uint32;
};
```

We currently reject this code.

```console
$ spicyc -j sync.spicy
[error] sync.spicy:10:7: &synchronize cannot be used on field, look-ahead contains non-literals
[error] spicyc: aborting after errors
```

### PR DESCRIPTION
**Pull request by bbannier**
We previously would not detect `%synchronize-at` or `%synchronize-from` attributes if the unit was not directly in a field, i.e., we mishandled the common case of synchronizing on a unit in a list.

With this patch we now handle these attributes, regardless of how the unit appears.

Closes #1617.

### CODE REVIEW

File: spicy/toolchain/src/compiler/codegen/parser-builder.cc [hunk 1]
```diff
@@ -1141,10 +1142,22 @@ struct ProductionVisitor
...
+        std::optional<type::Unit> unitType;
+        if ( while_ ) {
+            if ( const auto& field = while_->meta().field() )
+                if ( auto unit = field->parseType().elementType().tryAs<type::Unit>() )
+                    unitType = *unit;
+        }
+
+        else if ( const auto& unit = p->tryAs<production::Unit>() ) {
+            unitType = unit->unitType();
+        }
```
Comment (rsmmr) [inline spicy/toolchain/src/compiler/codegen/parser-builder.cc:1156]:
```suggestion
        else if ( const auto& unit = p->tryAs<production::Unit>() )
            unitType = unit->unitType();
```

**Review by rsmmr — APPROVED** [review]

File: spicy/toolchain/src/compiler/codegen/parser-builder.cc (hunk 1 above)
Comment (bbannier) [reply spicy/toolchain/src/compiler/codegen/parser-builder.cc:1156]: I actually thought of that, but incorrectly went with symmetry with the first case ;). Fixed.
