### PR TITLE
Fix synchronization with symbol different from last lookahead token.

### LINKED ISSUE #1774: Parse failure after successful synchronizaiton with `%synchronize-at`
Using `%synchronize-at` with regexp to sync a unit which expects to parse a `bytes` literal synchronizes successfully, but the unit still fails to parse. If I instead use a `bytes` literal for `%synchronize-at` the unit can continue parsing. I see this since about 57debb2d3abb3a89690d10991b1ddfd5e3198e14.

```ruby
module foo;

type A = unit {
    # %synchronize-at = b"A";
    %synchronize-at = /A/;

    a: b"A";
};

public type X = unit {
    : (A &synchronize)[] foreach {
        print $$;
    }

    on %synced {
        print "synced";
        confirm;
    }
};
```

```console
$ printf 'ABBAA' | HILTI_DEBUG=spicy-verbose spicy-driver -d foo.spicy
[spicy-verbose] - state: type=foo::X input="ABBAA" stream=0x600003404218 offsets=0/0/0/5 chunks=1 frozen=yes mode=default trim=yes lah=n/a lah_token="n/a" recovering=no
[spicy-verbose] - parsing production: Unit: foo__X -> _anon_2
[spicy-verbose]   - state: type=foo::X input="ABBAA" stream=0x600003404218 offsets=0/0/0/5 chunks=1 frozen=yes mode=default trim=yes lah=n/a lah_token="n/a" recovering=no
[spicy-verbose]   - parsing production: While: _anon_2 -> while(<look-ahead-found>): Resolved_3
[spicy-verbose]     - state: type=foo::X input="ABBAA" stream=0x600003404218 offsets=0/0/0/5 chunks=1 frozen=yes mode=default trim=yes lah=1 lah_token="A" recovering=no
[spicy-verbose]     - parsing production: Unit: foo__A_2 -> a_2 (container '_anon_2')
[spicy-verbose]       - state: type=foo::A input="ABBAA" stream=0x600003404218 offsets=0/0/0/5 chunks=1 frozen=yes mode=default trim=yes lah=1 lah_token="A" recovering=no
[spicy-verbose]       - parsing production: Ctor: a   -> b"A" (const bytes)
[spicy-verbose]         - consuming look-ahead token
[spicy-verbose]         - trimming input
[spicy-verbose]         - trimming input
[spicy-verbose]       - setting field 'a' to 'A'
[spicy-verbose]     - got container item
[$a=b"A"]
[spicy-verbose]     failed to parse list element, will try to synchronize at next possible element
[spicy-verbose]     - trimming input
[spicy-verbose]     - state: type=foo::X input="BAA" stream=0x600003404218 offsets=2/0/2/5 chunks=1 frozen=yes mode=default trim=yes lah=n/a lah_token="n/a" recovering=yes
[spicy-verbose]     - state: type=foo::X input="BAA" stream=0x600003404218 offsets=2/0/2/5 chunks=1 frozen=yes mode=default trim=yes lah=n/a lah_token="n/a" recovering=yes
[spicy-verbose]     - trimming input
[spicy-verbose]     - state: type=foo::X input="AA" stream=0x600003404218 offsets=3/0/3/5 chunks=1 frozen=yes mode=default trim=yes lah=2 lah_token="A" recovering=yes
[spicy-verbose]     successfully synchronized
synced
[spicy-verbose]     failed to parse list element, will try to synchronize at next possible element
[spicy-verbose]     - trimming input
[spicy-verbose]     - state: type=foo::X input="A" stream=0x600003404218 offsets=4/0/4/5 chunks=1 frozen=yes mode=default trim=yes lah=2 lah_token="A" recovering=yes
[spicy-verbose]     successfully synchronized
synced
[spicy-verbose]     failed to parse list element, will try to synchronize at next possible element
[spicy-verbose]     - trimming input
[error] terminating with uncaught exception of type spicy::rt::ParseError: failed to synchronize: no expected look-ahead token found (foo.spicy:11:5-13:5)

### PR DESCRIPTION
**Pull request by bbannier**
If `synchronize-[at|after]` used a lookahead symbol different from the last lookahead symbol (e.g., normal parsing used a literal, recovery a regexp), synchronization would clobber the lookahead symbol so that after successful synchronization normal parsing could still not succeed.

This patch sets up dedicated parser state for synchronization to prevent the clobbering.

Closes #1774.

### CODE REVIEW

File: spicy/toolchain/src/compiler/codegen/parser-builder.cc [hunk 1]
```diff
@@ -1241,7 +1242,7 @@ struct ProductionVisitor : public production::Visitor {
                 e = synchronize_after->expression();
 
             if ( e ) {
-                const auto id = "synchronize";
+                const auto id = hilti::util::fmt("synchronize_%u", std::hash<Meta>{}(e->meta()));
```
Comment (rsmmr) [inline spicy/toolchain/src/compiler/codegen/parser-builder.cc:1245]: Does this actually need to be considering the location/meta, or does it just need to be unique? If the latter, better to use `uniquer()->get("synchronize")`, for consistency and to avoid depending on the content of meta.

File: spicy/toolchain/src/compiler/codegen/parser-builder.cc [hunk 2]
```diff
@@ -1239,17 +1242,28 @@ struct ProductionVisitor : public production::Visitor {
...
                 assert(ctor_);
                 auto ctor = std::make_unique<production::Ctor>(context(), cg()->uniquer()->get(id), ctor_->ctor(),
                                                                ctor_->meta().location());
+
+                // We might use a different look-ahead for synchronization that
+                // for regular parsing at this position, e.g., due to
+                // `%synchronize-[at|after]`, so temporarily set a new value.
+                auto pstate = state();
+                auto sync_lahead = builder()->addTmp("sync_lahead", builder()->id("__lah"));
+                pstate.lahead = sync_lahead;
```
Comment (rsmmr) [inline spicy/toolchain/src/compiler/codegen/parser-builder.cc:1256]:
```suggestion
                pstate.lahead = builder()->addTmp("sync_lahead", builder()->id("__lah"));
```

**Review by rsmmr — APPROVED** [review]

File: spicy/toolchain/src/compiler/codegen/parser-builder.cc (hunk 1 above)
Comment (bbannier) [reply spicy/toolchain/src/compiler/codegen/parser-builder.cc]: It doesn't and the uniquer seems to see enough to handle this correctly, fixed.
