### PR TITLE
Fix AST inconsistency with how modules were stored in scopes.

### LINKED ISSUE #248: Internal error when passing Module where declaration expected
With fb1616d0adcc12433b97aba32804ee251fac2765 the following code triggers an internal error,
```
$ cat data/foo.spicy
module Foo;
print Foo;
```
```
$ spicyc -p data/foo.spicy
[internal-error] data/foo.spicy:1-2: ID 'Foo' resolved to something else than a declaration (hilti::Module)

--- Aborting
# 0   libhilti.dylib                      0x0000000104a8f894 _ZN5hilti2rt9BacktraceC2Ev + 84
# 1   libhilti.dylib                      0x0000000104b52548 _ZN4util20abort_with_backtraceEv + 136
# 2   libhilti.dylib                      0x0000000104b4cf57 _ZN5hilti6Logger13internalErrorERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS_8LocationE + 55
# 3   libhilti.dylib                      0x0000000104e77bfb _ZN5hilti6detail8lookupIDERKNS_2IDERKNS_4NodeE + 3163
# 4   libhilti.dylib                      0x0000000104e01f6e _ZN5hilti8lookupIDINS_11declaration6detail11DeclarationEEENS_2rt6ResultINSt3__14pairINS_7NodeRefENS_2IDEEEEERKS9_RKNS_7visitor8PositionIRNS_4NodeEEE + 190
# 5   libhilti.dylib                      0x0000000104dfe535 _ZN5hilti6detail7visitor11do_dispatchIvNS_10expression6detail10ExpressionEN12_GLOBAL__N_17VisitorENS1_8IteratorINS_4NodeELNS1_5OrderE0ELb0EEEEENSt3__111conditionalIXsr3stdE9is_void_vIT_EEbNSC_8optionalISE_EEE4typeERT0_RT1_RNT2_8PositionERb + 6853
# 6   libhilti.dylib                      0x0000000104dfa7d8 _ZN5hilti6detail7visitor11do_dispatchIvNS_4NodeEN12_GLOBAL__N_17VisitorENS1_8IteratorIS3_LNS1_5OrderE0ELb0EEEEENSt3__111conditionalIXsr3stdE9is_void_vIT_EEbNS9_8optionalISB_EEE4typeERT0_RT1_RNT2_8PositionERb + 8136
# 7   libhilti.dylib                      0x0000000104df853a _ZN5hilti6detail10resolveIDsEPNS_4NodeEPNS_4UnitE + 490
# 8   libhilti.dylib                      0x0000000104cf445a _Z17runModifyingHooksIMN5hilti6PluginENSt3__18optionalINS2_8functionIFbNS2_10shared_ptrINS0_7ContextEEEPNS0_4NodeEPNS0_4UnitEEEEEEJS7_S9_SB_EEbPbT_RKNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEDpRKT0_ + 650
# 9   libhilti.dylib                      0x0000000104cf163e _ZN5hilti4Unit7compileEv + 4974
# 10  libhilti.dylib                      0x0000000104cd8734 _ZN5hilti6Driver12_compileUnitENS_4UnitE + 836
# 11  libhilti.dylib                      0x0000000104cd95d4 _ZN5hilti6Driver12compileUnitsEv + 820
# 12  libhilti.dylib                      0x0000000104cdac0a _ZN5hilti6Driver7compileEv + 42
# 13  libhilti.dylib                      0x0000000104cda67d _ZN5hilti6Driver3runEv + 349
# 14  spicyc                              0x00000001042843c3 main + 99
# 15  libdyld.dylib                       0x00007fff6de7dcc9 start + 1
# 16  ???                                 0x0000000000000003 0x0 + 3
```
This should instead be caught in validation.

### PR DESCRIPTION
**Pull request by rsmmr**
Normally all scope entries should be pointing to declarations, but we
made an exception for "Module", which was inserted into the scope
directly. This commit introduces a separate "declaration::Module"
wrapper so that we can insert that into the scope, avoiding that
exception.

With that in place, we can then easily catch if an ID refers directly
to a module, which has no use case.

For the record: I did consider removing the current "Module" node
class altogether, and simply replacing it with "declaration::Module".
However, "Module" is special in that it's our only mutable AST node,
and it didn't feel right to mix that in with the other, non-mutable
declarations.

Closes #248.

### CODE REVIEW

File: hilti/include/ast/declarations/module.h [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+
+#pragma once
+
+#include <utility>
+
+#include <hilti/ast/declaration.h>
+#include <hilti/ast/expression.h>
+#include <hilti/ast/id.h>
+#include <hilti/ast/module.h>
+#include <hilti/base/result.h>
```
Comment (bbannier) [inline hilti/include/ast/declarations/module.h:11]: Let's include all required headers.
```suggestion

#include <hilti/ast/declaration.h>
#include <hilti/ast/expression.h>
#include <hilti/ast/id.h>
#include <hilti/ast/meta.h>
#include <hilti/ast/module.h>
#include <hilti/ast/node.h>
#include <hilti/ast/node_ref.h>
#include <hilti/base/result.h>
#include <hilti/base/type_erase.h>
```

File: hilti/include/ast/declarations/module.h [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+/** AST node for an AST's top-level module declaration. */
+class Module : public NodeBase, public hilti::trait::isDeclaration {
+public:
+    /**
+     * Constructor.
+     *
+     * @param root reference to root node of module's AST; must be a ``Module`` node.
+     */
+    Module(NodeRef root, Meta m = Meta()) : NodeBase(std::move(m)), _root(std::move(root)) {
+        assert(_root->isA<hilti::Module>());
```
Comment (bbannier) [inline hilti/include/ast/declarations/module.h:25]:
```suggestion
        assert(_root && _root->isA<hilti::Module>());
```

File: hilti/include/ast/declarations/module.h [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+    }
+
+    Node& root() const { return *_root; }
+
+    bool operator==(const Module& other) const { return id() == other.id(); }
+
+    /** Implements `Declaration` interface. */
+    bool isConstant() const { return true; }
+    /** Implements `Declaration` interface. */
+    ID id() const { return (*_root).as<hilti::Module>().id(); }
```
Comment (bbannier) [inline hilti/include/ast/declarations/module.h:35]:
```suggestion
    ID id() const { return _root->as<hilti::Module>().id(); }
```

**Comment by duffy-corelight** [comment]
Documentation in section 7.3.3. Importing Spicy Modules says:  
Searches the module `NAME` (i.e., `NAME.spicy`) inside a sub-directory `X/Y/Z` along the search path, and then imports it.

Is the module NAME to file NAME.spicy linkage required? Is it enforced anywhere?

**Comment by rsmmr** [comment]
Yes, that's enforced by specifically looking for `NAME.spicy` when you import `NAME`.
