### PR TITLE
Reject uses of `self` in unit `&size` and `&max-size` attribute

### LINKED ISSUE #1466: Use of unset unit fields not rejected in unit `&size` attribute
The following unit:

```
module Test;

public type test = unit {
	tag: uint8;
	length: uint16;
	data: bytes &size=self.length;
} &size=self.length+3;
```

Terminates with the following error:

```
$ printf '\x00\x00\x03abc' | spicy-driver test.spicy
[error] terminating with uncaught exception of type hilti::rt::UnsetOptional: unset optional value (test.spicy:3:20-6:2)
```

Using a size-check with size being sourced from a field inside a unit is a really useful feature, especially for TLV protocols, where the value can contain other types that can try to exceed the boundaries of the outer type. I encountered this during the reimplementation of the TLS analyzer; the old binpac analyzer uses this kind of construct a lot. The new parser currently doesn’t do as much checking - and I stumbled across this while trying to add it.

### PR DESCRIPTION
**Pull request by bbannier**
Closes #1466.

### CODE REVIEW

File: spicy/toolchain/src/compiler/visitors/validator.cc [hunk 1]
```diff
@@ -579,6 +580,22 @@ struct VisitorPost : public hilti::visitor::PreOrder<void, VisitorPost>, public
                 if ( a.tag() == "&size" || a.tag() == "&max-size" ) {
                     if ( ! a.hasValue() )
                         error(fmt("%s must provide an expression", a.tag()), p);
+                    else {
+                        auto v = hilti::visitor::PreOrder<>();
+                        for ( auto i : v.walk(a.value()) ) {
+                            auto&& member = i.node.tryAs<operator_::unit::MemberNonConst>();
+                            if ( ! member || ! member->hasOp0() )
+                                continue;
```
Comment (rsmmr) [inline spicy/toolchain/src/compiler/visitors/validator.cc:588]: Is this needed? Wouldn't just any usage of `self` enough for rejection? (i.e., just check if `i` is  the `ResolvedID`.)

File: spicy/toolchain/src/compiler/visitors/validator.cc [hunk 2]
```diff
@@ -579,6 +580,22 @@ struct VisitorPost : public hilti::visitor::PreOrder<void, VisitorPost>, public
...
+
+                            auto&& self = member->op0().tryAs<hilti::expression::ResolvedID>();
+                            if ( ! self || self->id().str() != "self" )
+                                continue;
+
+                            error(fmt("%s expression cannot depend on information available only after parsing of unit",
```
Comment (rsmmr) [inline spicy/toolchain/src/compiler/visitors/validator.cc:594]: I'd make this more explicit: "... cannot use `self` because that depends on ...".

File: spicy/toolchain/src/compiler/visitors/validator.cc (hunk 1 above)
Comment (bbannier) [reply spicy/toolchain/src/compiler/visitors/validator.cc:588]: You are right, this e.g., fails to capture cases where `self` is passed to a function which accesses fields. I'll simplify this to reject all uses of `self`, regardless of context.

**Review by rsmmr — APPROVED** [review]
