### PR TITLE
Fix code generator to emit types correctly for transitive dependencies.

### LINKED ISSUE #1057: Transitive includes not handled correctly
Under certain setups imports of imported modules are not implicitly imported. It is important that this works 😅.

```.console
$ tail *.spicy
==> a.spicy <==
module a;

import spicy;

%byte-order=spicy::ByteOrder::Little;

public type A = unit {};

==> b.spicy <==
module b;

import a;
import spicy; # FIXME(bbannier): This should be implicit when importing `a`.

public type B = unit {
    a_: a::A;
};

==> c.spicy <==
module c;
import b;

==> d.spicy <==
module d;

import c;
```

When compiling both `c` and `d` this fails:

```.console
spicyc c.spicy d.spicy -j
/private/var/folders/ht/vtb0rkbd4ws15vx02xdb84zw0000gn/T/d_dc75e53109471175-38c9e38328e44a4.cc:13:58: error: no member named 'a' in namespace '__hlt'
        std::optional<::hilti::rt::ValueReference<__hlt::a::A>> a_{};
                                                  ~~~~~~~^
```

As marked in the source for `b.spicy` there also seems to be an issue of `a` correctly exporting its dependency on `spicy`.

### PR DESCRIPTION
**Pull request by rsmmr**
Closes #1057.

### CODE REVIEW

File: hilti/toolchain/include/compiler/unit.h [hunk 1]
```diff
@@ -173,7 +173,7 @@ class Unit {
     Result<CxxCode> cxxCode() const;
 
     /** Returns the list of dependencies registered for the unit so far. */
-    const auto& dependencies() { return _dependencies; }
+    std::vector<std::weak_ptr<Unit>> dependencies(bool recursive = false);
```
Comment (bbannier) [inline hilti/toolchain/include/compiler/unit.h:176]: This should be `const`.

File: hilti/toolchain/include/compiler/unit.h [hunk 2]
```diff
@@ -385,6 +385,9 @@ class Unit {
     // Recursively destroys the module's AST.
     void _destroyModule();
 
+    // Helper for depencencies() to recurse.
+    void _recursiveDependencies(std::vector<std::weak_ptr<Unit>>* dst, std::vector<const Unit*>* seen);
+
```
Comment (bbannier) [inline hilti/toolchain/include/compiler/unit.h:390]: Can we instead move this to a helper function in the `.cc` file and pass in the `Unit` arg via a parameter `const Unit&`?

File: hilti/toolchain/src/compiler/unit.cc [hunk 3]
```diff
@@ -307,6 +307,30 @@ Result<CxxCode> Unit::cxxCode() const {
...
+
+    for ( const auto& d : _dependencies ) {
+        if ( std::find(seen->begin(), seen->end(), d.lock().get()) != seen->end() )
+            continue;
+
+        dst->push_back(d);
+        seen->push_back(d.lock().get());
+        d.lock()->_recursiveDependencies(dst, seen);
+    }
+}
```
Comment (bbannier) [inline hilti/toolchain/src/compiler/unit.cc:322]: Couple of comments:

- I think this would be better as a standalone, hidden function
- a `vector` `seen` seems like an unneeded pessimization for repeated searches, let's use a `unordered_set` instead (which also makes the code for search much shorter).
- let's avoid repeatedly locking the `weak_ptr` as this could become expensive

```suggestion
void _recursiveDependencies(const Unit& unit, std::vector<std::weak_ptr<Unit>>* dst,
                            std::unordered_set<const Unit*>* seen) {
    // This uses two vectors because the weak_ptr are a bit tough to work with,
    // in particular they can't be compared through std::find().

    for ( const auto& d : unit.dependencies(false) ) {
        auto* dep = d.lock().get();
        if ( seen->count(dep) )
            continue;

        dst->push_back(d);
        seen->insert(dep);
        _recursiveDependencies(*dep, dst, seen);
    }
}
```

File: tests/spicy/types/unit/transitive-imports.spicy [hunk 4]
```diff
@@ -0,0 +1,35 @@
+# @TEST-EXEC: spicyc c.spicy d.spicy -j
```
Comment (bbannier) [inline tests/spicy/types/unit/transitive-imports.spicy:1]:
```suggestion
# @TEST-EXEC: spicyc -d -j c.spicy d.spicy
```

File: hilti/toolchain/include/compiler/unit.h [hunk 5]
```diff
@@ -173,7 +173,7 @@ class Unit {
     Result<CxxCode> cxxCode() const;
 
     /** Returns the list of dependencies registered for the unit so far. */
```
Comment (bbannier) [inline hilti/toolchain/include/compiler/unit.h:175]: Let's document the new parameter.

**Review by bbannier — APPROVED** [review]

File: hilti/toolchain/include/compiler/unit.h (hunk 2 above)
Comment (rsmmr) [reply hilti/toolchain/include/compiler/unit.h:390]: The function needs access to the `_dependencies` member, so we'd need to friend it, which doesn't seem like it would help much.

**Review by bbannier — APPROVED** [review]
