### PR TITLE
Fix optimizer regression.

### LINKED ISSUE #1831: Optimizer leaves incorrect code
Something's off with the optimizer in 1.11:

```
# spicyc  -p tests/spicy/types/unit/underscores-in-ids.spicy
module Test {

import hilti;
import spicy_rt;

type Foo = struct {
    uint<32> x &optional;
    vector<Foo_> y &optional;
    optional<hilti::RecoverableFailure> __error &always-emit &internal;
    hook void __on_x(uint<32> __dd);
} &on-heap;

[... some Foo functions, but no further types ...]
}
```

It removes all the other `Foo_*` types, but leaves `Foo` in, and then `Foo` still refers to the now removed `Foo_`.

This is a regression, it works with 1.10, which outputs:

```
type Foo = struct {
    uint<32> x &optional;
    vector<Foo_> y &optional;
    optional<hilti::RecoverableFailure> __error &always-emit &internal;
    hook void __on_x(uint<32> __dd);
} &on-heap;
type Foo_ = struct {
    value_ref<Foo__> v &optional;
    optional<hilti::RecoverableFailure> __error &always-emit &internal;
} &on-heap;
type Foo__ = struct {
    value_ref<Foo___> v &optional;
    optional<hilti::RecoverableFailure> __error &always-emit &internal;
} &on-heap;
type Foo___ = struct {
    uint<8> v &optional;
    optional<hilti::RecoverableFailure> __error &always-emit &internal;
} &on-heap;
```
 I.e., it leaves the other types in, which at least lets the code remain valid.

### PR DESCRIPTION
**Pull request by rsmmr**
We were no longer marking types as used that are referenced through a
type name.

Closes #1831.

### CODE REVIEW

File: hilti/toolchain/src/compiler/optimizer.cc [hunk 1]
```diff
@@ -583,6 +583,26 @@ struct TypeVisitor : OptimizerVisitor {
         }
     }
 
+    void operator()(type::Name* n) final {
+        auto t = n->resolvedType();
+        assert(t);
```
Comment (bbannier) [inline hilti/toolchain/src/compiler/optimizer.cc:588]: Nit: I wonder whether we actually _need_ the `assert` here and couldn't instead return early like in many other places in this file. An unresolved `type::Name` shouldn't be "used" if we never needed to resolve it; it's likely some internal inconsistency, but we do not need to abort for it here.

**Review by bbannier — APPROVED** [review]

File: hilti/toolchain/src/compiler/optimizer.cc (hunk 1 above)
Comment (rsmmr) [reply hilti/toolchain/src/compiler/optimizer.cc:588]: At this point a name expression should never be left unresolved, the validator would have caught that and aborted. I was debating if we need the check at all, just felt better to have the assert just in case.
