### PR TITLE
Make generated grammar symbols globally unique during Spicy codegen.

### LINKED ISSUE #531: Look aheads which contain another look ahead fail to compile
This script...
```
module Test;

import spicy;

public type Line = unit {
  switch {
     -> a  : A;
     -> b  : B;
  };
};

type A = unit {
  switch {
    -> x : X;
    -> y : Y;
  };
};

type B = unit {
  val: /abc/;
};

type X = unit {
  val: /xyz/;
};

type Y = unit {
  val: /XYZ/;
};
```

Fails to compile with this error...
```
[error] /x/broken-la-in-la.spicy:2:1-30:3: redefinition of '__re_switch_lha_2' defined in /x/broken-la-in-la.spicy:2:1-30:3
[error] spicy-dump: aborting after errors
```

### PR DESCRIPTION
**Pull request by rsmmr**
With nested productions, we could end up generating colissions.

Closes #531.

### CODE REVIEW

File: spicy/toolchain/include/compiler/detail/codegen/codegen.h [hunk 1]
```diff
@@ -52,6 +54,7 @@ class CodeGen {
     NodeRef preserveNode(Expression x);
     NodeRef preserveNode(Statement x);
     NodeRef preserveNode(Type x);
+    auto uniquer() { return &_uniquer; }
```
Comment (bbannier) [inline spicy/toolchain/include/compiler/detail/codegen/codegen.h:57]: Not a real issue here, but it would be nice if this method could return a `const` pointer instead to be more in line with the overall spirit of this class. That would probably require some changes to `Cache` so it can provide a `const` interface over internally `mutable` state.

Feel free to ignore.

File: spicy/toolchain/src/compiler/codegen/grammar-builder.cc [hunk 2]
```diff
@@ -19,14 +19,14 @@ using hilti::util::fmt;
...
-    Visitor(codegen::GrammarBuilder* gb, Grammar* g) : gb(gb), grammar(g) {}
+    Visitor(CodeGen* cg, codegen::GrammarBuilder* gb, Grammar* g) : cg(cg), gb(gb), grammar(g) {}
+    CodeGen* cg;
     codegen::GrammarBuilder* gb;
     Grammar* grammar;
 
     using CurrentField = std::pair<const spicy::type::unit::item::Field&, std::reference_wrapper<hilti::Node>&>;
     std::vector<CurrentField> fields;
     hilti::util::Cache<std::string, Production> cache;
-    hilti::util::Uniquer<std::string> uniquer;
```
Comment (bbannier) [inline spicy/toolchain/src/compiler/codegen/grammar-builder.cc:29]: We have another (`static`!) `Uniquer` in `type::unit::item::Field`. Do you think we could clean that one up as well as part of this work so we have uniquing always as a part of cg?

File: spicy/toolchain/include/compiler/detail/codegen/codegen.h [hunk 3]
```diff
@@ -4,12 +4,14 @@
 
 #include <memory>
 #include <unordered_set>
+#include <string>
```
Comment (bbannier) [inline spicy/toolchain/include/compiler/detail/codegen/codegen.h:7]: Should be added before the previous line.

File: spicy/toolchain/src/compiler/codegen/grammar-builder.cc (hunk 2 above)
Comment (rsmmr) [reply spicy/toolchain/src/compiler/codegen/grammar-builder.cc:29]: Don't see an easy an easy way to unify those as field doesn't have access to a codegen. That's ok: if it only needs to be unique across fields, it's ok to leave there.

**Review by bbannier — APPROVED** [review]
