### PR TITLE
Fix potential infinite loop when trimming data before stream.

### LINKED ISSUE #1554: Trimming before the head chunk of a stream leads to infinite loop
With #1551 we now emit more trim calls which is good. It however leads to an infinite loop with the `spicy.gap-recovery` test in the test suite of zeek/zeek. The issue there is that we hit a code path were would would like to trim with an offset before the head chunk of the stream (which was already previously trimmed).

### PR DESCRIPTION
**Pull request by bbannier**
Previously we would trigger an infinite loop if one tried to trim before the head chunk of a stream. In praxis this seem to have been no issue due to #1549 and us emitting way less calls to trim than possible.

This patch adds an explicit check whether we need to trim anything, and exits the low-level function early for such cases.

Closes #1554.

### CODE REVIEW

File: hilti/runtime/src/types/stream.cc [hunk 1]
```diff
@@ -112,6 +119,11 @@ void Chain::trim(const Offset& offset) {
             assert(_head->offset() == offset);
             break;
         }
+
+        else {
+            // Other offsets are already rejected before entering loop.
+            cannot_be_reached();
+        }
```
Comment (rsmmr) [inline hilti/runtime/src/types/stream.cc:126]:
```suggestion
        else
            // Other offsets are already rejected before entering loop.
            cannot_be_reached();
```

**Review by rsmmr — APPROVED** [review]

**Comment by bbannier** [comment]
Also backported to `release/1.8`.
