### PR TITLE
Fix generation of escaped C++ string literals.

### LINKED ISSUE #217: in a bytes constant, had to double backslash the two printable characters
To provide a bytes constant, I had to double backslash the two printable characters, i.e:
```
module tzDatetime;

# public type input0210324115000A21 = unit {
callWith0210324115000A21();

function callWith0210324115000A21() {
local contentExceptLast : bytes = b"\x02\x10\\x32\\x41\x15\x00\x0A"
}
```
else it reports:
```
3323 /usr/local/etc/tmp$printf "12\n" | spicy/build/bin/spicyc -j Issue_217_fwd_ref.spicy
tzDatetime.cc:24:47: error: hex escape sequence out of range
    hilti::rt::Bytes contentExceptLast = "\x02\x102A\x15\x00\n"_b;
                                              ^~~~~~
1 error generated.
[error] jit: failed to execute compilation action.
[error] jit: failed to compile C++ code unit tzDatetime to bitcode
[error] spicyc: JIT compilation failed
```

### PR DESCRIPTION
**Pull request by rsmmr**
Turns out we can't just encode non-printable characters as \xNN
because C++ compilers look for more than 2 digits when decoding
"\x...". Now using octal \NNN instead, that's always 3 digits.

Closes #217.

### CODE REVIEW

**Comment by rsmmr** [comment]
Will wait for CI with this too.

**Comment by bbannier** [comment]
> Will wait for CI with this too.

To pick up the latest CI setup you'd need push an updated version rebased on `master`.

File: hilti/include/base/util.h [hunk 1]
```diff
@@ -408,6 +408,15 @@ using hilti::rt::escapeBytes;
 using hilti::rt::escapeUTF8;
 using hilti::rt::expandEscapes;
 
+/**
+ * Wrapper for `escapeBytes` that produces a valid C++ string literal.
+ *
+ * @param str string to escape
+ * @return escaped std::string (without the quotes)
```
Comment (bbannier) [inline hilti/include/base/util.h:415]: The `without the quotes` part made me pause. Are you talking about how literals are formatted in (input) C++ source code? -- in that case it should be clear that these quotes are not part of the literal itself, and I wouldn't expect them to be preserved when calling anything but possibly very arcane macros.
```suggestion
 * @return escaped std::string
```

File: hilti/include/base/util.h [hunk 2]
```diff
@@ -408,6 +408,15 @@ using hilti::rt::escapeBytes;
 using hilti::rt::escapeUTF8;
 using hilti::rt::expandEscapes;
 
+/**
+ * Wrapper for `escapeBytes` that produces a valid C++ string literal.
+ *
+ * @param str string to escape
```
Comment (bbannier) [inline hilti/include/base/util.h:414]:
```suggestion
 * @param s string to escape
```

Btw, there's a clang warning for errors like that, #240.

**Comment by duffy-corelight** [comment]
Using octal is not necessarily the solution. At https://en.cppreference.com/w/cpp/language/string_literal I read that: "If a valid hex digit follows a hex escape in a string literal, it would fail to compile as an invalid escape sequence. String concatenation can be used as a workaround."
const char* p = "\xfff"; // error: hex escape sequence out of range
const char* p = "\xff""f"; // OK: the literal is const char[3] holding {'\xff','f','\0'}

**Comment by rsmmr** [comment]
Yeah, I get the part on hex escapes (which I didn't know), but where do see that octal isn't going to work either?  From what I read, octal sequences are always the digits and hence don't run into the same problem.

(String concatenation would be another solution, but that seems more difficult to implemented, and it also just looks funny)

**Comment by duffy-corelight** [comment]
Oh if you have octal working, then go with that. I made this suggestion, because I envisioned that your problem space was for example, the .spicy being literally: b"\x7\4C", something like vector's to_string turning that into "\x07C" and then trying to use that in the Cxx source. Going byte-at-a-time, and always outputting the enclosing double-quotes, e.g. "\x07""C" would succeed in the Cxx source, and be a straightforward transformation. But if you have octal working, stick with that. I've had excellent success for years using the octal strategy. I just learned the literal string concatenation trick on the cppreference page at the above URL, yesterday.
